#pragma once
#include <stdint.h>

/**
 * OO Bridge - The Thought-to-Action Parser
 * 
 * Intercepts the raw token stream generated by the LLM.
 * If the AI generates specific command tags, the Bridge translates
 * those thoughts into kernel-level physical actions (Disk, Network, Memory).
 */

// Parses a sequence of tokens generated by the AI
// Returns 1 if a system command was executed (so the text shouldn't be displayed to the user)
// Returns 0 if it's just normal conversational text.
int oo_bridge_parse_thought(const char *thought_stream);

// Internal function triggered when the AI decides to mutate its environment
void oo_bridge_execute_morph(const char *domain);

// Absorbs characters one by one from the AI inference loop
// Buffers them until a full thought is formed, then parses it.
void oo_bridge_feed_char(char c);
